server:
  port: 8081
  servlet:
    context-path: /dev
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/community?useUnicode=true&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: always
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
mybatis:
  mapper-locations: classpath:/mapper/*.xml
